### ISSUE TITLE
ArgumentError during timeout

### ISSUE THREAD

**Issue by guss77** [showbox-oss/ffmprb#11]
seems to be a bug in threaded_io_buffer's handling of timeouts. When there's a timeout error we get:

```
ArgumentError raised in buffer reader thread: wrong number of arguments (0 for 1..2)
Backtrace:
        /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/timeout.rb:124:in `timeout'
        /var/www/workflows-service/shared/bundle/ruby/2.2.0/gems/ffmprb-0.9.2/lib/ffmprb/util/threaded_io_buffer.rb:122:in `rescue in block in init_reader!'
        /var/www/workflows-service/shared/bundle/ruby/2.2.0/gems/ffmprb-0.9.2/lib/ffmprb/util/threaded_io_buffer.rb:115:in `block in init_reader!'
```

The line in questions has:

```
fail Error, "Looks like we're stuck (#{timeout}s idle) with #{self.class.blocks_max}...
```

where `timeout` should be referenced as `self.class.timeout`. Otherwise it tries to call the kernel method `timeout`.

**Comment by costa** [comment]
thanks
